# Workflow setup for building Native Android project
workflows:
  android-app: # workflow ID
    name: Android app # workflow name
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - steveyong4@gmail.com